<a href="https://colab.research.google.com/github/morbosohex/Workflow/blob/master/Chararacter_Level_RNN%2C_Exercise-pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import os
os.chdir('/content/drive/My Drive/Colab Notebooks/AI算法工程师/字符级-LSTM-pytorch')

# Character-Level LSTM in PyTorch（文本生成）

在如下notebook文件中， 我们将用pytorch构建一个字符级LSTM模型，该网络将会在一些文本中一个字符接一个字符进行训练，然后再一个字符接一个字符的生成，该 notebook选择安娜卡列尼娜这本书进行训练，然后该训练后的模型会生成新的文本

该网络基于 Andrej Karpathy 的文章，[post on RNNs](http://karpathy.github.io/2015/05/21/rnn-effectiveness/) and [implementation in Torch](https://github.com/karpathy/char-rnn). 如下是字符级RNN的一般架构图

![image.png](https://upload-images.jianshu.io/upload_images/12735209-f9e999894c7ed8b7.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/800)


首先，让我们导入数据加载和模型创建所需的资源。

In [0]:

import numpy as np
import torch
from torch import nn
import torch.nn.functional as F

## 载入数据
载入安娜卡列尼娜文本文件，然后将其转化为网络接受的整数

### Tokenization

创建一对**dictionaries**, **一个转换字母为数字，一个将数字转换为字母，**


In [0]:
# open text file and read in data as `text`
with open('data/anna.txt', 'r') as f:
    text = f.read()

将上述字符串编码为数字

In [0]:
# encode the text and map each character to an integer and vice versa

# we create two dictonaries:
# 1. int2char, which maps integers to characters
# 2. char2int, which maps characters to unique integers
chars = tuple(set(text))
int2char = dict(enumerate(chars))
char2int = {ch: ii for ii, ch in int2char.items()}
encoded = np.array([char2int[ch] for ch in text])

让我们看看前100个字符，确保一切都是正常的。

In [6]:
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

检查将字符编码成数字的前100个字符

In [7]:
encoded[:100]

array([60, 62, 28, 80, 36, 53, 57, 13,  4, 72, 72, 72, 26, 28, 80, 80, 55,
       13, 65, 28, 44, 27, 14, 27, 53, 29, 13, 28, 57, 53, 13, 28, 14, 14,
       13, 28, 14, 27, 77, 53, 12, 13, 53, 49, 53, 57, 55, 13, 32, 21, 62,
       28, 80, 80, 55, 13, 65, 28, 44, 27, 14, 55, 13, 27, 29, 13, 32, 21,
       62, 28, 80, 80, 55, 13, 27, 21, 13, 27, 36, 29, 13, 56, 30, 21, 72,
       30, 28, 55, 11, 72, 72,  6, 49, 53, 57, 55, 36, 62, 27, 21])

## 数据前处理

如上图的架构图所示，LSTM网络期望得到的输入是，每个字符的独热向量



In [0]:
def one_hot_encode(arr, n_labels):
    
    # Initialize the the encoded array
    one_hot = np.zeros((np.multiply(*arr.shape), n_labels), dtype=np.float32)

    # Fill the appropriate elements with ones
    one_hot[np.arange(one_hot.shape[0]), arr.flatten()] = 1.
    
    # Finally reshape it to get back to the original array
    one_hot = one_hot.reshape((*arr.shape, n_labels))
    
    return one_hot

## 构建训练过程中的mini-batch

记住，批数据是有多个序列构成的，每个序列都有指定的序列步，如下图所示

![image.png](https://upload-images.jianshu.io/upload_images/12735209-6ff90c33d1953166.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/800)


<br>


In this example, we'll take the encoded characters (passed in as the `arr` parameter) and split them into multiple sequences, given by `n_seqs` (also refered to as "batch size" in other places). Each of those sequences will be `n_steps` long.

### Creating Batches

**1. The first thing we need to do is discard some of the text so we only have completely full batches. **

Each batch contains $N \times M$ characters, where $N$ is the batch size (the number of sequences) and $M$ is the number of steps. Then, to get the total number of batches, $K$, we can make from the array `arr`, you divide the length of `arr` by the number of characters per batch. Once you know the number of batches, you can get the total number of characters to keep from `arr`, $N * M * K$.

**2. After that, we need to split `arr` into $N$ sequences. ** 

You can do this using `arr.reshape(size)` where `size` is a tuple containing the dimensions sizes of the reshaped array. We know we want $N$ sequences, so let's make that the size of the first dimension. For the second dimension, you can use `-1` as a placeholder in the size, it'll fill up the array with the appropriate data for you. After this, you should have an array that is $N \times (M * K)$.

**3. Now that we have this array, we can iterate through it to get our batches. **

The idea is each batch is a $N \times M$ window on the $N \times (M * K)$ array. For each subsequent batch, the window moves over by `n_steps`. We also want to create both the input and target arrays. Remember that the targets are the inputs shifted over one character. The way I like to do this window is use `range` to take steps of size `n_steps` from $0$ to `arr.shape[1]`, the total number of steps in each sequence. That way, the integers you get from `range` always point to the start of a batch, and each window is `n_steps` wide.

> **TODO:** Write the code for creating batches in the function below. The exercises in this notebook _will not be easy_. I've provided a notebook with solutions alongside this notebook. If you get stuck, checkout the solutions. The most important thing is that you don't copy and paste the code into here, **type out the solution code yourself.**

In [0]:
def get_batches(arr, n_seqs, n_steps):
    '''Create a generator that returns batches of size
       n_seqs x n_steps from arr.
       
       Arguments
       ---------
       arr: Array you want to make batches from
       n_seqs: Batch size, the number of sequences per batch
       n_steps: Number of sequence steps per batch
    '''
    
    # Get the number of characters per batch
    batch_size = n_seqs * n_steps
    
    ## TODO: Get the number of batches we can make
    n_batches = len(arr) // batch_size
    
    ## TODO: Keep only enough characters to make full batches
    arr = arr[:batch_size*n_batches]
    
    ## TODO: Reshape into batch_size rows
    arr = arr.reshape((n_seqs,-1))
    
    ## TODO: Make batches
    for n in range(0, arr.shape[1], n_steps):
        # The features
        x = arr[:,n:n+n_steps]
        # The targets, shifted by one
        y = np.zeros_like(x)
        try:
            y[:, :-1], y[:, -1] = x[:, 1:], arr[:, n+n_steps]
        except IndexError:
            y[:, :-1], y[:, -1] = x[:, 1:], arr[:, 0]
            
        yield x, y


### Test Your Implementation

Now I'll make some data sets and we can check out what's going on as we batch data. Here, as an example, I'm going to use a batch size of 10 and 50 sequence steps.

In [0]:
batches = get_batches(encoded, 10, 50)
x, y = next(batches)

In [20]:
print('x\n', x[:10, :10])
print('\ny\n', y[:10, :10])

x
 [[60 62 28 80 36 53 57 13  4 72]
 [13 28 44 13 21 56 36 13 45 56]
 [49 27 21 11 72 72 75 23 53 29]
 [21 13 18 32 57 27 21 45 13 62]
 [13 27 36 13 27 29 52 13 29 27]
 [13 42 36 13 30 28 29 72 56 21]
 [62 53 21 13 59 56 44 53 13 65]
 [12 13 39 32 36 13 21 56 30 13]
 [36 13 27 29 21 68 36 11 13 63]
 [13 29 28 27 18 13 36 56 13 62]]

y
 [[62 28 80 36 53 57 13  4 72 72]
 [28 44 13 21 56 36 13 45 56 27]
 [27 21 11 72 72 75 23 53 29 52]
 [13 18 32 57 27 21 45 13 62 27]
 [27 36 13 27 29 52 13 29 27 57]
 [42 36 13 30 28 29 72 56 21 14]
 [53 21 13 59 56 44 53 13 65 56]
 [13 39 32 36 13 21 56 30 13 29]
 [13 27 29 21 68 36 11 13 63 62]
 [29 28 27 18 13 36 56 13 62 53]]


If you implemented `get_batches` correctly, the above output should look something like 
```
x
 [[55 63 69 22  6 76 45  5 16 35]
 [ 5 69  1  5 12 52  6  5 56 52]
 [48 29 12 61 35 35  8 64 76 78]
 [12  5 24 39 45 29 12 56  5 63]
 [ 5 29  6  5 29 78 28  5 78 29]
 [ 5 13  6  5 36 69 78 35 52 12]
 [63 76 12  5 18 52  1 76  5 58]
 [34  5 73 39  6  5 12 52 36  5]
 [ 6  5 29 78 12 79  6 61  5 59]
 [ 5 78 69 29 24  5  6 52  5 63]]

y
 [[63 69 22  6 76 45  5 16 35 35]
 [69  1  5 12 52  6  5 56 52 29]
 [29 12 61 35 35  8 64 76 78 28]
 [ 5 24 39 45 29 12 56  5 63 29]
 [29  6  5 29 78 28  5 78 29 45]
 [13  6  5 36 69 78 35 52 12 43]
 [76 12  5 18 52  1 76  5 58 52]
 [ 5 73 39  6  5 12 52 36  5 78]
 [ 5 29 78 12 79  6 61  5 59 63]
 [78 69 29 24  5  6 52  5 63 76]]
 ```
 although the exact numbers will be different. Check to make sure the data is shifted over one step for `y`.

---
## Defining the network with PyTorch

Below is where you'll define the network. We'll break it up into parts so it's easier to reason about each bit. Then we can connect them up into the whole network.

![image.png](https://upload-images.jianshu.io/upload_images/12735209-34366c60ce90a325.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/800)



Next, you'll use PyTorch to define the architecture of the network. We start by defining the layers and operations we want. Then, define a method for the forward pass. You've also been given a method for predicting characters.

### Model Structure

In `__init__` the suggested structure is as follows:
* Create and store the necessary dictionaries (this has been done for you)
* Define an LSTM layer that takes as params: an input size (the number of characters), a hidden layer size `n_hidden`, a number of layers `n_layers`, a dropout probability `drop_prob`, and a batch_first boolean (True, since we are batching)
* Define a dropout layer with `dropout_prob`
* Define a fully-connected layer with params: input size `n_hidden` and output size (the number of characters)
* Finally, initialize the weights (again, this has been given)

Note that some parameters have been named and given in the `__init__` function, and we use them and store them by doing something like `self.drop_prob = drop_prob`.

---
### LSTM Inputs/Outputs

You can create a basic LSTM cell as follows

```python
self.lstm = nn.LSTM(input_size, n_hidden, n_layers, 
                            dropout=drop_prob, batch_first=True)
```

where `input_size` is the number of characters this cell expects to see as sequential input, and `n_hidden` is the number of units in the hidden layers in the cell. And we can add dropout by adding a dropout parameter with a specified probability; this will automatically add dropout to the inputs or outputs. Finally, in the `forward` function, we can stack up the LSTM cells into layers using `.view`. With this, you pass in a list of cells and it will send the output of one cell into the next cell.

We also need to create an initial cell state of all zeros. This is done like so

```python
self.init_weights()
```

In [0]:
class CharRNN(nn.Module):
    
    def __init__(self, tokens, n_steps=100, n_hidden=256, n_layers=2,
                               drop_prob=0.5, lr=0.001):
        super().__init__()
        self.drop_prob = drop_prob
        self.n_layers = n_layers
        self.n_hidden = n_hidden
        self.lr = lr
        
        # creating character dictionaries
        self.chars = tokens
        self.int2char = dict(enumerate(self.chars))
        self.char2int = {ch: ii for ii, ch in self.int2char.items()}
        
        ## TODO: define the LSTM, self.lstm
        self.lstm = nn.LSTM(len(self.chars), n_hidden, n_layers, 
                                    dropout=drop_prob, batch_first=True)        
        ## TODO: define a dropout layer, self.dropout
        self.dropout = nn.Dropout(drop_prob)
        ## TODO: define the final, fully-connected output layer, self.fc
        self.fc = nn.Linear(n_hidden,len(self.chars))
        # initialize the weights
        self.init_weights()
      
    
    def forward(self, x, hc):
        ''' Forward pass through the network. 
            These inputs are x, and the hidden/cell state `hc`. '''
        
        ## TODO: Get x, and the new hidden state (h, c) from the lstm
        x,(h,c) = self.lstm(x,hc)
        ## TODO: pass x through a droupout layer
        x = self.dropout(x)
        # Stack up LSTM outputs using view
        x = x.view(x.size()[0]*x.size()[1], self.n_hidden)
        
        ## TODO: put x through the fully-connected layer
        x = self.fc(x)
        # return x and the hidden state (h, c)
        return x, (h, c)
    
    
    def predict(self, char, h=None, cuda=False, top_k=None):
        ''' Given a character, predict the next character.
        
            Returns the predicted character and the hidden state.
        '''
        if cuda:
            self.cuda()
        else:
            self.cpu()
        
        if h is None:
            h = self.init_hidden(1)
        
        x = np.array([[self.char2int[char]]])
        x = one_hot_encode(x, len(self.chars))
        inputs = torch.from_numpy(x)
        if cuda:
            inputs = inputs.cuda()
        
        h = tuple([each.data for each in h])
        out, h = self.forward(inputs, h)

        p = F.softmax(out, dim=1).data
        if cuda:
            p = p.cpu()
        
        if top_k is None:
            top_ch = np.arange(len(self.chars))
        else:
            p, top_ch = p.topk(top_k)
            top_ch = top_ch.numpy().squeeze()
        
        p = p.numpy().squeeze()
        char = np.random.choice(top_ch, p=p/p.sum())
            
        return self.int2char[char], h
    
    def init_weights(self):
        ''' Initialize weights for fully connected layer '''
        initrange = 0.1
        
        # Set bias tensor to all zeros
        self.fc.bias.data.fill_(0)
        # FC weights as random uniform
        self.fc.weight.data.uniform_(-1, 1)
        
    def init_hidden(self, n_seqs):
        ''' Initializes hidden state '''
        # Create two new tensors with sizes n_layers x n_seqs x n_hidden,
        # initialized to zero, for hidden state and cell state of LSTM
        weight = next(self.parameters()).data
        return (weight.new(self.n_layers, n_seqs, self.n_hidden).zero_(),
                weight.new(self.n_layers, n_seqs, self.n_hidden).zero_())
        

### A note on the `predict`  function

The output of our RNN is from a fully-connected layer and it outputs a **distribution of next-character scores**.

To actually get the next character, we apply a softmax function, which gives us a *probability* distribution that we can then sample to predict the next character.

In [0]:
## ---- keep notebook from crashing during training --- ##
import os
import requests
import time

def train(net, data, epochs=10, n_seqs=10, n_steps=50, lr=0.001, clip=5, val_frac=0.1, cuda=False, print_every=10):
    ''' Training a network 
    
        Arguments
        ---------
        
        net: CharRNN network
        data: text data to train the network
        epochs: Number of epochs to train
        n_seqs: Number of mini-sequences per mini-batch, aka batch size
        n_steps: Number of character steps per mini-batch
        lr: learning rate
        clip: gradient clipping
        val_frac: Fraction of data to hold out for validation
        cuda: Train with CUDA on a GPU
        print_every: Number of steps for printing training and validation loss
    
    '''
    
    net.train()
    opt = torch.optim.Adam(net.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()
    
    # create training and validation data
    val_idx = int(len(data)*(1-val_frac))
    data, val_data = data[:val_idx], data[val_idx:]
    
    if cuda:
        net.cuda()
    
    counter = 0
    n_chars = len(net.chars)
    

    for e in range(epochs):
        h = net.init_hidden(n_seqs)
        for x, y in get_batches(data, n_seqs, n_steps):
            

            
            counter += 1
            
            # One-hot encode our data and make them Torch tensors
            x = one_hot_encode(x, n_chars)
            inputs, targets = torch.from_numpy(x), torch.from_numpy(y)
            
            if cuda:
                inputs, targets = inputs.cuda(), targets.cuda()

            # Creating new variables for the hidden state, otherwise
            # we'd backprop through the entire training history
            h = tuple([each.data for each in h])

            net.zero_grad()
            
            output, h = net.forward(inputs, h)
            loss = criterion(output, targets.view(n_seqs*n_steps))

            loss.backward()
            
            # `clip_grad_norm` helps prevent the exploding gradient problem in RNNs / LSTMs.
            nn.utils.clip_grad_norm_(net.parameters(), clip)

            opt.step()
            
            if counter % print_every == 0:
                
                # Get validation loss
                val_h = net.init_hidden(n_seqs)
                val_losses = []
                for x, y in get_batches(val_data, n_seqs, n_steps):
                    # One-hot encode our data and make them Torch tensors
                    x = one_hot_encode(x, n_chars)
                    x, y = torch.from_numpy(x), torch.from_numpy(y)
                    
                    # Creating new variables for the hidden state, otherwise
                    # we'd backprop through the entire training history
                    val_h = tuple([each.data for each in val_h])
                    
                    inputs, targets = x, y
                    if cuda:
                        inputs, targets = inputs.cuda(), targets.cuda()

                    output, val_h = net.forward(inputs, val_h)
                    val_loss = criterion(output, targets.view(n_seqs*n_steps))
                
                    val_losses.append(val_loss.item())
                
                print("Epoch: {}/{}...".format(e+1, epochs),
                      "Step: {}...".format(counter),
                      "Loss: {:.4f}...".format(loss.item()),
                      "Val Loss: {:.4f}".format(np.mean(val_losses)))

## Time to train

现在我们可以实际训练网络。首先，我们将使用一些给定的超参数创建网络本身。然后，定义小批量大小（序列数和步数），并开始训练。通过训练函数，我们可以设置epoch数，学习率和其他参数。此外，我们可以通过设置`cuda = True`在GPU上运行训练。

In [0]:
if 'net' in locals():
    del net

In [28]:
# define and print the net
net = CharRNN(chars, n_hidden=1024, n_layers=2)
print(net)

CharRNN(
  (lstm): LSTM(83, 1024, num_layers=2, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.5)
  (fc): Linear(in_features=1024, out_features=83, bias=True)
)


In [31]:
n_seqs, n_steps = 128, 100

# you may change cuda to True if you plan on using a GPU!
# also, if you do, please INCREASE the epochs to 25

# Open the training log file.
log_file = 'training_log.txt'
f = open(log_file, 'w')

# TRAIN
train(net, encoded, epochs=25, n_seqs=n_seqs, n_steps=n_steps, lr=0.001, cuda=True, print_every=10)

# Close the training log file.
f.close()


Epoch: 1/25... Step: 10... Loss: 3.2159... Val Loss: 3.2313
Epoch: 1/25... Step: 20... Loss: 3.0154... Val Loss: 3.0316
Epoch: 1/25... Step: 30... Loss: 2.8305... Val Loss: 2.8046
Epoch: 1/25... Step: 40... Loss: 2.5942... Val Loss: 2.6268
Epoch: 1/25... Step: 50... Loss: 2.5401... Val Loss: 2.5171
Epoch: 1/25... Step: 60... Loss: 2.4193... Val Loss: 2.4474
Epoch: 1/25... Step: 70... Loss: 2.3703... Val Loss: 2.3971
Epoch: 1/25... Step: 80... Loss: 2.2927... Val Loss: 2.3506
Epoch: 1/25... Step: 90... Loss: 2.2884... Val Loss: 2.3110
Epoch: 1/25... Step: 100... Loss: 2.2295... Val Loss: 2.2768
Epoch: 1/25... Step: 110... Loss: 2.1836... Val Loss: 2.3426
Epoch: 1/25... Step: 120... Loss: 2.1129... Val Loss: 2.2580
Epoch: 1/25... Step: 130... Loss: 2.1367... Val Loss: 2.1808
Epoch: 2/25... Step: 140... Loss: 2.1007... Val Loss: 2.1500
Epoch: 2/25... Step: 150... Loss: 2.0673... Val Loss: 2.1281
Epoch: 2/25... Step: 160... Loss: 2.0492... Val Loss: 2.0884
Epoch: 2/25... Step: 170... Loss:

## 找到最佳模型

要设置超参数以获得最佳性能，您需要观察训练和验证损失。如果您的训练损失远低于验证损失，那么您就过度拟合了。增加正规化（更多丢失）或使用更小的网络。如果培训和验证损失很接近，那么表现为欠拟合，需要增加网络规模。

## 超参数

如下是网络的一些超参数

定义模型过程中：
* `n_hidden` - The number of units in the hidden layers.
* `n_layers` - Number of hidden LSTM layers to use.

We assume that dropout probability and learning rate will be kept at the default, in this example.

训练过程中:
* `n_seqs` - Number of sequences running through the network in one pass.
* `n_steps` - Number of characters in the sequence the network is trained on. Larger is better typically, the network will learn more long range dependencies. But it takes longer to train. 100 is typically a good number here.
* `lr` - Learning rate for training

Here's some good advice from Andrej Karpathy on training the network. I'm going to copy it in here for your benefit, but also link to [where it originally came from](https://github.com/karpathy/char-rnn#tips-and-tricks).

> ## 技巧

>### 监控Validation Loss vs. Training Loss
>If you're somewhat new to Machine Learning or Neural Networks it can take a bit of expertise to get good models. The most important quantity to keep track of is the difference between your training loss (printed during training) and the validation loss (printed once in a while when the RNN is run on the validation data (by default every 1000 iterations)). In particular:

> - If your training loss is much lower than validation loss then this means the network might be **overfitting**. Solutions to this are to decrease your network size, or to increase dropout. For example you could try dropout of 0.5 and so on.
> - If your training/validation loss are about equal then your model is **underfitting**. Increase the size of your model (either number of layers or the raw number of neurons per layer)

> ### Approximate number of parameters

> The two most important parameters that control the model are `n_hidden` and `n_layers`. I would advise that you always use `n_layers` of either 2/3. The `n_hidden` can be adjusted based on how much data you have. The two important quantities to keep track of here are:

> - The number of parameters in your model. This is printed when you start training.
> - The size of your dataset. 1MB file is approximately 1 million characters.

>These two should be about the same order of magnitude. It's a little tricky to tell. Here are some examples:

> - I have a 100MB dataset and I'm using the default parameter settings (which currently print 150K parameters). My data size is significantly larger (100 mil >> 0.15 mil), so I expect to heavily underfit. I am thinking I can comfortably afford to make `n_hidden` larger.
> - I have a 10MB dataset and running a 10 million parameter model. I'm slightly nervous and I'm carefully monitoring my validation loss. If it's larger than my training loss then I may want to try to increase dropout a bit and see if that helps the validation loss.

> ### Best models strategy

>The winning strategy to obtaining very good models (if you have the compute time) is to always err on making the network larger (as large as you're willing to wait for it to compute) and then try different dropout values (between 0,1). Whatever model has the best validation performance (the loss, written in the checkpoint filename, low is good) is the one you should use in the end.

>It is very common in deep learning to run many different models with many different hyperparameter settings, and in the end take whatever checkpoint gave the best validation performance.

>By the way, the size of your training and validation splits are also parameters. Make sure you have a decent amount of data in your validation set or otherwise the validation performance will be noisy and not very informative.

After training, we'll save the model so we can load it again later if we need too. Here I'm saving the parameters needed to create the same architecture, the hidden layer hyperparameters and the text characters.

In [0]:
# change the name, for saving multiple files
model_name = 'rnn_1_epoch.net'

checkpoint = {'n_hidden': net.n_hidden,
              'n_layers': net.n_layers,
              'state_dict': net.state_dict(),
              'tokens': net.chars}

with open(model_name, 'wb') as f:
    torch.save(checkpoint, f)

## Sampling

Now that the model is trained, we'll want to sample from it. To sample, we pass in a character and have the network predict the next character. Then we take that character, pass it back in, and get another predicted character. Just keep doing this and you'll generate a bunch of text!

### Top K sampling

Our predictions come from a categorcial probability distribution over all the possible characters. We can make the sample text and make it more reasonable to handle (with less variables) by only considering some $K$ most probable characters. This will prevent the network from giving us completely absurd characters while allowing it to introduce some noise and randomness into the sampled text.

Typically you'll want to prime the network so you can build up a hidden state. Otherwise the network will start out generating characters at random. In general the first bunch of characters will be a little rough since it hasn't built up a long history of characters to predict from.

In [0]:
def sample(net, size, prime='The', top_k=None, cuda=False):
        
    if cuda:
        net.cuda()
    else:
        net.cpu()

    net.eval()
    
    # First off, run through the prime characters
    chars = [ch for ch in prime]
    h = net.init_hidden(1)
    for ch in prime:
        char, h = net.predict(ch, h, cuda=cuda, top_k=top_k)

    chars.append(char)
    
    # Now pass in the previous character and get a new one
    for ii in range(size):
        char, h = net.predict(chars[-1], h, cuda=cuda, top_k=top_k)
        chars.append(char)

    return ''.join(chars)

In [35]:
print(sample(net, 2000, prime='Anna', top_k=5, cuda=False))

Anna, the called
commission in the first second too was never a perfect silence to the part
the cloth and the secret comin out of the minds, and the colonel
was seeking at the eact of his childhood and a peasant, all of his own
foreseeing the servant came out on his study, and, took the carriage drooping in
the bedroom door of their way how show it with the steps in the morning
was so shrugg, his hands had already seen for the fact that
his father always did, and again all disappointed their portraits in his
heart and something should be fine with these springing and corn work and
socras and household and intensely conversation it with his since had been
plained in the proposed thick and stranker in the chair and sat a
man of the same delicate figure to him.

Anna did not answer, but what she would drive it at heallowy. Though the
most contentious, one of the changing pain of the man with his fance and
children, and taking the second, holding up his head to his, and wet all
at his brot

## Loading a checkpoint

In [36]:
# Here we have loaded in a model that trained over 1 epoch `rnn_1_epoch.net`
with open('rnn_1_epoch.net', 'rb') as f:
    checkpoint = torch.load(f)
    
loaded = CharRNN(checkpoint['tokens'], n_hidden=checkpoint['n_hidden'], n_layers=checkpoint['n_layers'])
loaded.load_state_dict(checkpoint['state_dict'])

IncompatibleKeys(missing_keys=[], unexpected_keys=[])

In [37]:
# Change cuda to True if you are using GPU!
print(sample(loaded, 2000, cuda=False, top_k=5, prime="And Levin said"))

And Levin said:

"That is what I can't feel that I am nice and there. These
thousand about me on her soul a forest that's in the whole day. What is
simple one of my profess?" and a servant with which they had taken
a little chook off to the silence when she had time to say that
their conversation had been discovered, but she did not see, which
would have the same society of again at home, where she went into the
room.

"Ah! I should never have done that in all the theirs are
proposed to all our horses. The colonel, the changing old man or
a certainty privided any other service, and that he was almost at home the
conversation was so strong that it was all the same that and a stock
of and was a general suncession, and any other peasants were to be
seen from the timid of the committee would try to start the little old
man.

Levin was not in to be seen before. But he could not submit. Alexey
Alexandrovitch, smiling tone of the princess to wait the supple sight of
the leather with a corns o